spring:
  application:
    name: consumer-demo-feign
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    addresses: 10.0.20.132
    port: 5672
    username: root
    password: root
  zipkin:
    rabbitmq:
      queue: zipkin
server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  hystrix:
    enabled: true
